driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
    run_list:
    - recipe[yum-epel]
  - name: centos-6.7
    run_list:
    - recipe[yum-epel]
  - name: centos-7.1
  - name: debian-7.8
    run_list: apt::default
  - name: debian-8.1
    run_list: apt::default
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
- name: default
  run_list:  
  - recipe[runit_test]
  attributes: {}

- name: service
  run_list:
  - recipe[runit_test::service]
  attributes: {}
