driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
    run_list: yum::dnf_yum_compat
  - name: oracle-6.8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[runit_test]

- name: service
  run_list:
  - recipe[runit_test::service]
