driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.6
  - name: fedora-21
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[runit_test]
  - recipe[runit-other_test]
  attributes: {}

- name: service
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[runit_test::service]
  - recipe[runit-other_test]
  attributes: {}
