driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: oracle-6
  - name: oracle-7
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[runit_test]

- name: service
  run_list:
  - recipe[runit_test::service]
