AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false

# HashSyntax:
#  EnforcedStyle: hash_rockets

Documentation:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'tmp/**/*'
    - 'cookbooks/**/*'

Style/GuardClause:
  Enabled: false

# TODO: remove override for ModuleLength once RunitCookbook::Helpers has been refactored
Metrics/ModuleLength:
  Max: 150
