name 'runit_other_test'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'Apache 2.0'
description 'This cookbook is used with test-kitchen to test the "template cookbook" option in the runit cookbook'
version '1.0.0'
